### ISSUE TITLE
Unbound module Stdlib when trying to check a basic erlang module

### ISSUE THREAD

**Issue by michallepicki** [AbstractMachinesLab/caramel#4]
On the [latest release page](https://github.com/AbstractMachinesLab/caramel/releases/tag/v0.0.3) I saw an interesting point:

> new command for type-checking erlang: caramelc check

And I wanted to try this out. So I downloaded the release, created a basic erlang module and saw this:

```
$ caramelc check mymodule.erl 
Unbound module Stdlib$ cat mymodule.erl 
-module(mymodule).

-export([hey/0]).

hey() ->
    ok.
```

What am I doing wrong?

**Comment by michallepicki** [comment]
As a note, I think it would be nice if the `caramelc` added a newline at the end of the output for the tty

**Comment by mseri** [comment]
The error happens when the runtime cannot determine the OCaml standard library in its lookup path. I don't think you are doing anything wrong, maybe something needs to be done to make the released binary more portable?

The same happens on my mac, with ocaml 4.11.1 and 4.10.1 installed

**Comment by michallepicki** [comment]
I didn't even know `ocaml` was needed for that feature, so I don't have it installed. I thought the compiler is a self-contained statically linked executable (but I guess maybe I could have predicted it if its main purpose is to compile ocaml code...)

**Comment by mseri** [comment]
That is what I was expecting as well, and why I was surprised to see your comment. Maybe it is just a matter of adding or removing a compilation flag. Are you using mac or linux?

On linux I think it also links glibc, for relocatable builds I usually use alpine for that reason.

**Comment by michallepicki** [comment]
My system information, if you think it may be useful. It uses glibc:
```
$ uname -a
Linux michalspc 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27
```

**Comment by ostera** [comment]
Hi @michallepicki and thanks for reporting this! :) -- I'll try to replicate this over lunch and get back to you.

**Comment by ostera** [comment]
Managed to replicate 👍🏼 -- I'll write back here any progress.

**Comment by ostera** [comment]
Alright so I managed to pack _a_ Stdlib with the release. Truth is the OCaml stdlib as it is is not very useful anyway, and I'll have to patch it up as I go to make the compilation more idiomatic.

As of the next tag, the release will be a tarball of two things:
- caramelc.exe
- stdlib (dir)

As long as those two are in the same directory, you should not get an `Unbound module Stdlib` error.

**Comment by ostera** [comment]
So I got a few things in, including publishing build artifacts on every job (so I am not forced to cut a release until its actually releasable 😅 ) -- would you  mind trying one of these? 

https://github.com/AbstractMachinesLab/caramel/actions/runs/282176647

Not sure if that link is fully public, so here's both linux builds: 
[caramel-main-x86_64-linux-musl.tar.gz](https://github.com/AbstractMachinesLab/caramel/files/5311432/caramel-main-x86_64-linux-musl.tar.gz)
[caramel-main-x86_64-linux-gnu.tar.gz](https://github.com/AbstractMachinesLab/caramel/files/5311433/caramel-main-x86_64-linux-gnu.tar.gz)

**Comment by michallepicki** [comment]
@ostera 
```
$ caramelc.exe check mymodule.erl 
caramelc.exe: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by caramelc.exe)
caramelc.exe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by caramelc.exe)
```

**Comment by ostera** [comment]
Of course, latest ubuntu is running glibc_2.31 -- I may need to build on ubuntu-16.04 for the gnu build, and use 20.04 for the musl one.

Its running now on main... 🤞🏼

**Comment by michallepicki** [comment]
@ostera I am still running 18.04, my glibc version seems to be `2.27`, sorry for that. I would understand if you want to support only the latest ubuntu.

**Comment by ostera** [comment]
There's a few packages that I'd have to backport (i think) to get a 16.04 build against glibc_2.23-ish -- so instead I'll build against 18.04 which is what I was building against before.

Sorry this whole glibc thing got tangled in! 🙌🏼

**Comment by ostera** [comment]
@michallepicki keep an eye open for this one: https://github.com/AbstractMachinesLab/caramel/actions/runs/282255225 -- the gnu binary should be built against glibc 2.27 🚀

**Comment by michallepicki** [comment]
It runs! Does something, writes two files `.cmo` and `.cmi` and returns the process with success status (`0`) for this module. Closing! Thank you, I'll tinker with this more some other time.

**Comment by ostera** [comment]
Awesome! Thanks for opening this issue 🙌🏼 

Yes, the `.cmo` and `.cmi` are some of the compilation artifacts. If you get those, it means the sources type-checked correctly, and they can be used to speed up type-checks of dependent modules (and to break caches, etc).

These are artifacts of the OCaml compiler toolchain, and are really more useful when working with a build system like [dune](https://dune.build) or (shameless plug) [crane](https://github.com/AbstractMachinesLab/crane).
